apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: personal-website
  name: personal-website
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"personal-website"},"name":"personal-website"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"personal-website"}},"template":{"metadata":{"labels":{"app":"personal-website"}},"spec":{"containers":[{"image":"europe-north1-docker.pkg.dev/fleet-tractor-432310-d8/personal-repo/personal-website:latest","name":"personal-website"}]}}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      # placeholder <GCP_PROJECT_ID> is substituted in deployment workflow
      - image: europe-north1-docker.pkg.dev/<GCP_PROJECT_ID>/personal-repo/gardberg/personal-website:latest
        name: personal-website
